FPR                                                                     

FOIP                                                                  

FGIP                                                                

WBHP                                   
  /                              

FWPR                                   
FOPR                                   
FGPR                                                                     
FOPT                                   
FGPT                                   
FWPT

FOE
-- Pore Volume at Reservoir conditions
FRPV                                                           

FWCT                                   

TIMESTEP 

NEWTON